### ISSUE TITLE
I failed to get or set to get brightness on the extended monitor

### ISSUE THREAD

**Issue by legendhill** [tigerlily-dev/Monitor-Configuration-Class#1]
I failed to get or set to get brightness on the extended monitor
![16117j_20221217_195316_18](https://user-images.githubusercontent.com/79631683/208240511-8d445aad-88a8-4978-b818-9e317a5246ae.png)
![49117j_20221217_195349_10](https://user-images.githubusercontent.com/79631683/208240539-8303aefe-0ce3-4a76-9661-21e6e64f6664.png)

**Comment by pattazl** [comment]
I have the same issue , when GetBrightness(2) ,it crashed

**Comment by 348bestbox** [comment]
This code is very outdated using an old v2 alpha version. I recommend rewriting this to meet the current v2 version's conventions. I'm a bit too busy with other things to really look into this, but that could be your problem.

**Comment by pattazl** [comment]
OK, I will try to rewrite , it is very strange , it works well when only 1 montior , if have more , it crashed.

**Comment by pattazl** [comment]
#Include  ".\Monitor Class.ahk" 
mon := Monitor()
MsgBox(mon.GetBrightness(2)["Current"])   ; it will crashed when have more than 1 monitor in laptop, but it worked well in desktop compute.
